### ISSUE TITLE
Initialize Spring web application

### ISSUE THREAD

**Issue by iv21dk** [DOGGER152/dv_spring_web_mongo#1]
Требуется создать приложение на основе Spring Boot, предоставляющее следующий
REST интерфейс:

GET /api/projects - получить список проектов (описание каждого проекта содержит id и имя проекта)
POST /api/projects - создать новый проект (параметр name содержит имя проекта)
GET /api/projects/{id} - получить описание проекта по id проекта (описание содержит id и имя проекта)
PUT /api/projects/{id} - изменить имя проекта
DELETE /api/projects/{id} - удалить проект по id

Проекты должны сохраняться в БД MongoDb с помощью Spring Data.
Используйте аннотации для конфигурации (не XML).
Каждый проект имеет уникальное имя.
--------------------------------------------------------

Пример проверки работоспособности приложения с помощью утилиты curl (https://curl.haxx.se/windows/):

Получить пустой список проектов в начале работы:
>curl localhost:8080/api/projects
[]

Создать новый проект с именем "prj1":
>curl -i -d "name=prj1" localhost:8080/api/projects
HTTP/1.1 201
Location: /api/projects/1
Content-Length: 0
Date: ...

Получить список проектов (он должен содержать описание созданного проекта):
>curl localhost:8080/api/projects
[{"id":1,"name":"prj1"}]

Получить описание созданного проекта:
>curl localhost:8080/api/projects/1
{"id":1,"name":"prj1"}

Изменить имя проекта (берётся строка "project1" из файла params.txt):
>curl -T params.txt localhost:8080/api/projects/1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    12    0     4  100     8     51    102 --:--:-- --:--:-- --:--:--   153true

Получить список проектов, содержащий описание изменённого проекта с новым именем:
>curl localhost:8080/api/projects
[{"id":1,"name":"project1"}]

Удалить проект по id:
>curl -X DELETE localhost:8080/api/projects/1

Проверить, что список проектов пустой:
>curl localhost:8080/api/projects
[]

--------------------------------------------------------

Лучше всего создать приложение на базе Spring Initializer
https://start.spring.io/

Java: 11
Maven project
Dependencies: WEB, Spring Data MongoDB

**Comment by DOGGER152** [comment]
Done
